{% set name = "pykrb5" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/krb5/krb5-{{ version }}.tar.gz
  sha256: 4cdd2c85ff4770108edaf48fedf19888cf956ff374e2e97e40f8412b048caee6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - krb5
    - python
    - cython >=0.29.32,<4.0.0
    - setuptools >=42.0.0
    - pip
  run:
    - cryptography >=1.3
    - krb5
    - python

test:
  imports:
    - krb5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pykrb5
  summary: Kerberos API bindings for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iamthebot
